sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install: pip install tox
before_script:
- ".travis/bump_version ./ ${AUTOVERSION_INCREMENT} > damster/VERSION"
script:
- tox
deploy:
  provider: pypi
  user: cattz
  distributions: sdist bdist_wheel
  skip_cleanup: true
  password:
    secure: wkGIXiYjNBmc0gJL6wJctrGatHQD0WY5vGsJ0WyCWcbRQk+CXkCPGfsDwdnBQGY7mJY6yy0wOV0QE6kB/a6qnSVkTZMZppc4vZYyjYHbU0daH0Ly99Mn4OCLQm0ReB+5ORMALlK1CaQiFIPfT94x4IC/G/sZeWwH8HBkpGxrLYzMjo+bZqV4zJp06CEzwursOXYSVOboSdRLIca8i3l4bITQiWinDC5m+H3Ty+Yosw12HtL3oc3c9e570YEmFme3+C+0iITeTctqoBygmTew4qu3R2IaNeQpx1WCshb8v23hVBYBFcsUeeVtCXkXHeSji2V6IY2hlgQoZfGigQRkUrXKBZ0QGS5b/WRxHymh4qb47EppRA1AerSGD1EJ0S40ijrpixE6hbWVqLhsShGlfgszCOAZ83LmdaBeOpc3mrT0IhgnL3azjuG0EQ07OsduhTKk9Yfi5o0FGKgyJwNBvbHAr/fFNN0ZncPSO0WvcD3kYPy9UqTCFCR4hioV87/Ua5L24tRwYMeYkPlTR3cWJRcezxGEDihmksiSoKNr6Zb6m6NXWUEpK4cZYzLGkjm+8HPxzKFT+yFZlvHJvtOuvWTjB3+IzfMVjwVPWfhtFZK4vmOgpjpSvNlhyCfNNNXRh5f4de13Ss/oQhchgNzXRVEs5Fg31Cmh7aH83Cb9rCg=
  on:
    branch: master
    python: 3.5
